// Canonical list of supported coding agents, in display order. Shared by the
// marketing landing carousel and the dashboard auth/expired gate so the two
// surfaces can't drift. Names are tooltip/a11y metadata only.
export const AGENT_LOGOS = [
  { id: 1, name: "Claude Code", provider: "claude" },
  { id: 2, name: "Codex", provider: "codex" },
  { id: 3, name: "Cursor", provider: "cursor" },
  { id: 4, name: "Gemini", provider: "gemini" },
  { id: 5, name: "Antigravity", provider: "antigravity" },
  { id: 6, name: "Kiro", provider: "kiro" },
  { id: 7, name: "OpenCode", provider: "opencode" },
  { id: 8, name: "OpenClaw", provider: "openclaw" },
  { id: 9, name: "Every Code", provider: "every-code" },
  { id: 10, name: "Hermes", provider: "hermes" },
  { id: 11, name: "GitHub Copilot", provider: "copilot" },
  { id: 12, name: "Kimi", provider: "kimi" },
  { id: 13, name: "CodeBuddy", provider: "codebuddy" },
  { id: 14, name: "WorkBuddy", provider: "workbuddy" },
  { id: 15, name: "Grok", provider: "grok" },
  { id: 16, name: "oh-my-pi", provider: "omp" },
  { id: 17, name: "Pi", provider: "pi" },
  { id: 18, name: "Craft", provider: "craft" },
  { id: 19, name: "Reasonix", provider: "reasonix" },
  { id: 20, name: "Kilo CLI", provider: "kilo-cli" },
  { id: 21, name: "Kilo Code", provider: "kilocode" },
  { id: 22, name: "Roo Code", provider: "roocode" },
  { id: 23, name: "Zed", provider: "zed" },
  { id: 24, name: "Goose", provider: "goose" },
  { id: 25, name: "Droid", provider: "droid" },
  { id: 26, name: "Mimo", provider: "mimo" },
  { id: 27, name: "ZCode", provider: "zcode" },
  { id: 28, name: "Qoder", provider: "qoder" },
  { id: 29, name: "AnythingLLM", provider: "anythingllm" },
  { id: 30, name: "Claude Science", provider: "claude-science" },
  { id: 31, name: "DeepSeek Harness", provider: "dsh" },
];
